package com.yucareux.tellus.api;

import com.yucareux.tellus.world.data.resolve.ResolveEcoregion;
import com.yucareux.tellus.world.data.resolve.TellusResolveSource;
import com.yucareux.tellus.world.realtime.TellusRealtimeState;
import com.yucareux.tellus.world.realtime.TemperatureGrid;
import com.yucareux.tellus.worldgen.EarthChunkGenerator;
import com.yucareux.tellus.worldgen.EarthGeneratorSettings;
import com.yucareux.tellus.worldgen.EarthProjection;
import com.yucareux.tellus.worldgen.TellusWorldgenSources;
import java.util.Objects;
import java.util.Optional;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.chunk.ChunkGenerator;

/**
 * Stable, intentionally small entry points for companion mods such as Tellus Expeditions.
 *
 * <p>Everything here delegates to Tellus internals that may be reorganised between releases; companions
 * should depend on this class rather than on {@code com.yucareux.tellus.worldgen} or
 * {@code com.yucareux.tellus.world.data} directly. Sampling methods are safe to call off-thread and never
 * require chunks to be generated; they read Tellus' cached rasters and download tiles on demand, so the
 * first call for a new area may block on network I/O.</p>
 */
public final class TellusApi {
   /** Incremented whenever a method here changes signature or semantics. */
   public static final int API_VERSION = 1;

   private TellusApi() {
   }

   /** Returns the Earth generator of {@code level} when the level is a Tellus world. */
   public static Optional<EarthChunkGenerator> earthGenerator(ServerLevel level) {
      Objects.requireNonNull(level, "level");
      ChunkGenerator generator = level.getChunkSource().getGenerator();
      return generator instanceof EarthChunkGenerator earth ? Optional.of(earth) : Optional.empty();
   }

   /** True when the level is generated by Tellus. */
   public static boolean isEarthLevel(ServerLevel level) {
      return earthGenerator(level).isPresent();
   }

   /** Real-world terrain elevation in metres above sea level at a block column, or {@code NaN} when unavailable. */
   public static double elevationMeters(double blockX, double blockZ, double worldScale) {
      return TellusWorldgenSources.elevation().sampleElevationMeters(blockX, blockZ, worldScale);
   }

   /**
    * Elevation from tiles already on disk or in memory only; never downloads. Returns {@code NaN} for
    * unexplored areas. Use this from the server thread for positions the player is not standing on.
    */
   public static double elevationMetersLocalOnly(double blockX, double blockZ, double worldScale) {
      return TellusWorldgenSources.elevation()
         .samplePreviewElevationMetersLocalOnly(blockX, blockZ, worldScale, false, EarthGeneratorSettings.DEFAULT.demSelection(), worldScale);
   }

   /** Terrain slope in degrees from already cached elevation tiles only, or {@code NaN} when not cached yet. */
   public static double slopeDegreesLocalOnly(double blockX, double blockZ, double worldScale) {
      return TellusWorldgenSources.elevation().sampleTerrainSlopeDegreesLocalOnly(blockX, blockZ, worldScale);
   }

   /** ESA WorldCover class code (10 tree cover .. 100 moss/lichen, 0 no data) at a block column. */
   public static int landCoverClass(double blockX, double blockZ, double worldScale) {
      return TellusWorldgenSources.landCover().sampleCoverClass(blockX, blockZ, worldScale);
   }

   /** Koppen-Geiger code such as {@code "Cfb"} at a block column, or {@code null} when unknown. */
   public static String koppenCode(double blockX, double blockZ, double worldScale) {
      return TellusWorldgenSources.koppen().sampleRawCode(blockX, blockZ, worldScale);
   }

   /** RESOLVE 2017 ecoregion metadata at a block column; {@link ResolveEcoregion#UNKNOWN} when unavailable. */
   public static ResolveEcoregion ecoregion(double blockX, double blockZ, double worldScale) {
      return TellusResolveSource.shared().sampleEcoregion(blockX, blockZ, worldScale);
   }

   /** Latest real-world 2 m air temperature near {@code pos} in Celsius, or {@code NaN} when no data is loaded. */
   public static float realTemperatureC(BlockPos pos) {
      return TellusRealtimeState.realWorldTemperatureC(pos);
   }

   /** The current real-world temperature grid (possibly empty). */
   public static TemperatureGrid temperatureGrid() {
      return TellusRealtimeState.temperatureGrid();
   }

   /** Current real-time precipitation mode; {@code CLEAR} when real-time weather is off. */
   public static TellusRealtimeState.PrecipitationMode precipitationMode() {
      return TellusRealtimeState.precipitationMode();
   }

   /** True when real-time weather data is actively driving the level's weather. */
   public static boolean isRealtimeWeatherActive() {
      return TellusRealtimeState.isWeatherEnabled();
   }

   public static double latitudeFromBlockZ(double blockZ, double worldScale) {
      return EarthProjection.blockZToLat(blockZ, worldScale);
   }

   public static double longitudeFromBlockX(double blockX, double worldScale) {
      return EarthProjection.blockXToLongitude(blockX, worldScale);
   }

   public static double blockZFromLatitude(double latitude, double worldScale) {
      return EarthProjection.latToBlockZ(latitude, worldScale);
   }

   public static double blockXFromLongitude(double longitude, double worldScale) {
      return EarthProjection.longitudeToBlockX(longitude, worldScale);
   }

   /** Real ground metres covered by one block along X or Z at the given block row (Mercator corrected). */
   public static double groundMetersPerBlock(double blockZ, double worldScale) {
      return EarthProjection.groundMetersPerBlockX(blockZ, worldScale);
   }
}
