package com.yucareux.tellus.api;

import com.yucareux.tellus.api.detail.ChunkDetailContributor;
import com.yucareux.tellus.api.detail.ChunkDetailContributorRegistry;
import com.yucareux.tellus.world.data.resolve.ResolveEcoregion;
import com.yucareux.tellus.world.data.resolve.TellusResolveSource;
import com.yucareux.tellus.world.realtime.TellusRealtimeState;
import com.yucareux.tellus.world.realtime.TemperatureGrid;
import com.yucareux.tellus.worldgen.EarthChunkGenerator;
import com.yucareux.tellus.worldgen.EarthGeneratorSettings;
import com.yucareux.tellus.worldgen.TellusWorldgenSources;
import com.yucareux.tellus.worldgen.WorldProjection;
import java.util.Objects;
import java.util.Optional;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.chunk.ChunkGenerator;

/**
 * Stable, intentionally small entry points for optional integrations.
 *
 * <p>Everything here delegates to Tellus internals that may be reorganised between releases; integrations
 * should depend on this class rather than on {@code com.yucareux.tellus.worldgen} or
 * {@code com.yucareux.tellus.world.data} directly. Sampling methods are safe to call off-thread and never
 * require chunks to be generated; they read Tellus' cached rasters and download tiles on demand, so the
 * first call for a new area may block on network I/O.</p>
 */
public final class TellusApi {
   /** Incremented whenever a method here changes signature or semantics. */
   public static final int API_VERSION = 6;

   private TellusApi() {
   }

   /**
    * Registers an optional chunk-detail contributor for Earth generators created afterward.
    *
    * <p>Registration identifiers determine deterministic arbitration order. Register during common
    * initialization, before a server begins loading worlds.</p>
    */
   public static ChunkDetailContributorRegistry.Registration registerChunkDetailContributor(
      String identifier,
      ChunkDetailContributor contributor
   ) {
      return ChunkDetailContributorRegistry.global().register(identifier, contributor);
   }

   /** Returns the Earth generator of {@code level} when the level is a Tellus world. */
   public static Optional<EarthChunkGenerator> earthGenerator(ServerLevel level) {
      Objects.requireNonNull(level, "level");
      ChunkGenerator generator = level.getChunkSource().getGenerator();
      return generator instanceof EarthChunkGenerator earth ? Optional.of(earth) : Optional.empty();
   }

   /** True when the level is generated by Tellus. */
   public static boolean isEarthLevel(ServerLevel level) {
      return earthGenerator(level).isPresent();
   }

   /** The exact per-world projection, including an optional spawn-centred origin. */
   public static WorldProjection projection(EarthChunkGenerator generator) {
      return Objects.requireNonNull(generator, "generator").settings().projection();
   }

   /**
    * True when Tellus has finished every deferred terrain/detail write for an already-loaded chunk.
    * Companion world decorators should wait for this before changing surface blocks. The probe never
    * loads, generates, schedules or waits for a chunk.
    */
   public static boolean isChunkDetailReady(ServerLevel level, int chunkX, int chunkZ) {
      return earthGenerator(Objects.requireNonNull(level, "level"))
         .map(generator -> generator.isChunkDetailReady(level, chunkX, chunkZ))
         .orElse(false);
   }

   /** Real-world terrain elevation in metres above sea level at a block column, or {@code NaN} when unavailable. */
   public static double elevationMeters(double blockX, double blockZ, WorldProjection projection) {
      return TellusWorldgenSources.elevation().sampleElevationMeters(blockX, blockZ, projection);
   }

   /**
    * Elevation from tiles already on disk or in memory only; never downloads. Returns {@code NaN} for
    * unexplored areas. Use this from the server thread for positions the player is not standing on.
    */
   public static double elevationMetersLocalOnly(double blockX, double blockZ, WorldProjection projection) {
      return TellusWorldgenSources.elevation()
         .samplePreviewElevationMetersLocalOnly(
            blockX,
            blockZ,
            projection,
            false,
            EarthGeneratorSettings.DEFAULT.demSelection(),
            projection.worldScale()
         );
   }

   /** Terrain slope in degrees from already cached elevation tiles only, or {@code NaN} when not cached yet. */
   public static double slopeDegreesLocalOnly(double blockX, double blockZ, WorldProjection projection) {
      return TellusWorldgenSources.elevation().sampleTerrainSlopeDegreesLocalOnly(blockX, blockZ, projection);
   }

   /** ESA WorldCover class code (10 tree cover .. 100 moss/lichen, 0 no data) at a block column. */
   public static int landCoverClass(double blockX, double blockZ, WorldProjection projection) {
      return TellusWorldgenSources.landCover().sampleCoverClass(blockX, blockZ, projection);
   }

   /** Koppen-Geiger code such as {@code "Cfb"} at a block column, or {@code null} when unknown. */
   public static String koppenCode(double blockX, double blockZ, WorldProjection projection) {
      return TellusWorldgenSources.koppen().sampleRawCode(blockX, blockZ, projection);
   }

   /** RESOLVE 2017 ecoregion metadata at a block column; {@link ResolveEcoregion#UNKNOWN} when unavailable. */
   public static ResolveEcoregion ecoregion(double blockX, double blockZ, WorldProjection projection) {
      return TellusResolveSource.shared().sampleEcoregion(blockX, blockZ, projection);
   }

   /** Latest real-world 2 m air temperature near {@code pos} in Celsius, or {@code NaN} when no data is loaded. */
   public static float realTemperatureC(BlockPos pos) {
      return TellusRealtimeState.realWorldTemperatureC(pos);
   }

   /** The current real-world temperature grid (possibly empty). */
   public static TemperatureGrid temperatureGrid() {
      return TellusRealtimeState.temperatureGrid();
   }

   /** Current real-time precipitation mode; {@code CLEAR} when real-time weather is off. */
   public static TellusRealtimeState.PrecipitationMode precipitationMode() {
      return TellusRealtimeState.precipitationMode();
   }

   /** True when real-time weather data is actively driving the level's weather. */
   public static boolean isRealtimeWeatherActive() {
      return TellusRealtimeState.isWeatherEnabled();
   }

   public static double latitudeFromBlockZ(double blockZ, WorldProjection projection) {
      return projection.blockZToLat(blockZ);
   }

   public static double longitudeFromBlockX(double blockX, WorldProjection projection) {
      return projection.blockXToLon(blockX);
   }

   public static double blockZFromLatitude(double latitude, WorldProjection projection) {
      return projection.latToBlockZ(latitude);
   }

   public static double blockXFromLongitude(double longitude, WorldProjection projection) {
      return projection.lonToBlockX(longitude);
   }

   /** Real ground metres covered by one block along X or Z at the given block row (Mercator corrected). */
   public static double groundMetersPerBlock(double blockZ, WorldProjection projection) {
      return projection.groundMetersPerBlockX(blockZ);
   }
}
